namespace BMMDL.Runtime.Services;

using BMMDL.MetaModel.Structure;
using BMMDL.MetaModel.Service;
using BMMDL.MetaModel.Utilities;
using BMMDL.Runtime.Expressions;
using Microsoft.Extensions.Logging;
using Npgsql;

/// <summary>
/// Executes actions/functions via PostgreSQL stored procedures.
/// Uses the PL/pgSQL functions generated by PgSqlActionGenerator.
/// </summary>
public class DatabaseActionExecutor : IActionExecutor
{
    private readonly string _connectionString;
    private readonly string _schemaName;
    private readonly ILogger<DatabaseActionExecutor> _logger;

    public DatabaseActionExecutor(
        string connectionString,
        ILogger<DatabaseActionExecutor> logger,
        string schemaName = "public")
    {
        _connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _schemaName = schemaName;
    }

    public async Task<ActionResult> ExecuteActionAsync(
        BmEntity entity,
        BmAction action,
        Guid entityId,
        Dictionary<string, object?> parameters,
        EvaluationContext context,
        CancellationToken ct = default)
    {
        var result = new ActionResult();
        var functionName = GetFunctionName(entity.Name, action.Name);

        _logger.LogInformation("Executing database action {Schema}.{Function} for entity {EntityId}",
            _schemaName, functionName, entityId);

        try
        {
            await using var conn = new NpgsqlConnection(_connectionString);
            await conn.OpenAsync(ct);

            await using var cmd = conn.CreateCommand();
            cmd.CommandText = BuildActionCallSql(functionName, action, parameters);
            
            // Add parameters
            cmd.Parameters.AddWithValue("p_id", entityId);
            cmd.Parameters.AddWithValue("p_user_id", context.User?.Id ?? (object)DBNull.Value);
            cmd.Parameters.AddWithValue("p_tenant_id", context.TenantId ?? (object)DBNull.Value);
            
            foreach (var param in action.Parameters)
            {
                var paramName = $"p_{NamingConvention.ToSnakeCase(param.Name)}";
                var value = parameters.TryGetValue(param.Name, out var v) ? v : DBNull.Value;
                cmd.Parameters.AddWithValue(paramName, value ?? DBNull.Value);
            }

            // Execute and get result
            var dbResult = await cmd.ExecuteScalarAsync(ct);
            result.Value = dbResult == DBNull.Value ? null : dbResult;
            result.Success = true;

            _logger.LogInformation("Database action {Function} completed successfully", functionName);
        }
        catch (PostgresException ex)
        {
            _logger.LogError(ex, "Database action {Function} failed: {Message}", functionName, ex.Message);
            result.Success = false;
            result.ErrorMessage = ex.MessageText;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error executing database action {Function}", functionName);
            result.Success = false;
            result.ErrorMessage = ex.Message;
        }

        return result;
    }

    public async Task<FunctionResult> ExecuteFunctionAsync(
        BmEntity entity,
        BmFunction function,
        Guid entityId,
        Dictionary<string, object?> parameters,
        EvaluationContext context,
        CancellationToken ct = default)
    {
        var result = new FunctionResult();
        var functionName = GetFunctionName(entity.Name, function.Name);

        _logger.LogInformation("Executing database function {Schema}.{Function} for entity {EntityId}",
            _schemaName, functionName, entityId);

        try
        {
            await using var conn = new NpgsqlConnection(_connectionString);
            await conn.OpenAsync(ct);

            await using var cmd = conn.CreateCommand();
            cmd.CommandText = BuildFunctionCallSql(functionName, function, parameters);
            
            // Add parameters
            cmd.Parameters.AddWithValue("p_id", entityId);
            
            foreach (var param in function.Parameters)
            {
                var paramName = $"p_{NamingConvention.ToSnakeCase(param.Name)}";
                var value = parameters.TryGetValue(param.Name, out var v) ? v : DBNull.Value;
                cmd.Parameters.AddWithValue(paramName, value ?? DBNull.Value);
            }

            // Execute and get result
            var dbResult = await cmd.ExecuteScalarAsync(ct);
            result.Value = dbResult == DBNull.Value ? null : dbResult;
            result.Success = true;

            _logger.LogInformation("Database function {Function} completed", functionName);
        }
        catch (PostgresException ex)
        {
            _logger.LogError(ex, "Database function {Function} failed: {Message}", functionName, ex.Message);
            result.Success = false;
            result.ErrorMessage = ex.MessageText;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error executing database function {Function}", functionName);
            result.Success = false;
            result.ErrorMessage = ex.Message;
        }

        return result;
    }

    public async Task<bool> IsFunctionDeployedAsync(BmEntity entity, string operationName, CancellationToken ct = default)
    {
        var functionName = GetFunctionName(entity.Name, operationName);
        
        try
        {
            await using var conn = new NpgsqlConnection(_connectionString);
            await conn.OpenAsync(ct);

            await using var cmd = conn.CreateCommand();
            cmd.CommandText = @"
                SELECT EXISTS (
                    SELECT 1 FROM pg_proc p
                    JOIN pg_namespace n ON p.pronamespace = n.oid
                    WHERE n.nspname = @schema AND p.proname = @name
                )";
            cmd.Parameters.AddWithValue("schema", _schemaName);
            cmd.Parameters.AddWithValue("name", functionName);

            var result = await cmd.ExecuteScalarAsync(ct);
            return result is true;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Error checking if function {Function} is deployed", functionName);
            return false;
        }
    }

    private string GetFunctionName(string entityName, string operationName) =>
        $"{NamingConvention.ToSnakeCase(entityName)}_{NamingConvention.ToSnakeCase(operationName)}";

    private string BuildActionCallSql(string functionName, BmAction action, Dictionary<string, object?> parameters)
    {
        var paramList = new List<string> { "@p_id", "@p_user_id", "@p_tenant_id" };
        
        foreach (var param in action.Parameters)
        {
            paramList.Add($"@p_{NamingConvention.ToSnakeCase(param.Name)}");
        }

        return $"SELECT {_schemaName}.{functionName}({string.Join(", ", paramList)})";
    }

    private string BuildFunctionCallSql(string functionName, BmFunction function, Dictionary<string, object?> parameters)
    {
        var paramList = new List<string> { "@p_id" };
        
        foreach (var param in function.Parameters)
        {
            paramList.Add($"@p_{NamingConvention.ToSnakeCase(param.Name)}");
        }

        return $"SELECT {_schemaName}.{functionName}({string.Join(", ", paramList)})";
    }
}
